_cqa_uarch_const = {
  ["RS_ALU2 size"] = 24,
  ["ports"] = {
    ["FP ADD"] = {
      [1] = 10,
      [2] = 11,
    },
    ["store address"] = {
      [1] = 5,
      [2] = 6,
      [3] = 7,
    },
    ["FP store data"] = {
      [1] = 12,
      [2] = 13,
    },
    ["DIV/SQRT"] = {
      [1] = 9,
    },
    ["load"] = {
      [1] = 5,
      [2] = 6,
      [3] = 7,
    },
    ["misc"] = {
      [1] = 0,
      [2] = 1,
      [3] = 2,
      [4] = 3,
      [5] = 4,
    },
    ["VPU"] = {
      [1] = 8,
      [2] = 9,
      [3] = 10,
      [4] = 11,
    },
    ["FP FMA"] = {
      [1] = 8,
      [2] = 9,
    },
    ["FP MUL"] = {
      [1] = 8,
      [2] = 9,
    },
  },
  ["load unit native width"] = 32,
  ["RS_ALU1 size"] = 24,
  ["LFB size"] = 24,
  ["RS_ALU0 size"] = 24,
  ["predicted taken branch ports"] = {
    [1] = 0,
  },
  ["ROB size"] = 256,
  ["INT vector size in bytes"] = 32,
  ["vector size in bytes"] = 32,
  ["aliases"] = {
    ["RS_ALU0"] = "ALQ0",
    ["RS_VPU0"] = "VPQ0",
    ["RS_ALU2"] = "ALQ2",
    ["LFB"] = "MAB",
    ["RS_ALU1"] = "ALQ1",
    ["SB"] = "STQ",
    ["RS_ALU3"] = "ALQ3",
    ["ROB"] = "RQ",
    ["LB"] = "LDQ",
    ["RS_VPU1"] = "VPQ1",
  },
  ["RS_ALU3 size"] = 24,
  ["store unit native width"] = 32,
  ["UQ throughput"] = 6,
  ["RS_VPU1 size"] = 32,
  ["RS_VPU0 size"] = 32,
  ["IQ throughput"] = 4,
  ["PRF_FLOAT size"] = 160,
  ["uop cache capacity"] = 2600,
  ["store latency"] = 3,
  ["load latency"] = 4,
  ["NOP 0f 1f decode"] = "fast",
  ["retire throughput"] = 8,
  ["UFS resources"] = {
    [1] = "ROB",
    [2] = "RS_ALU0",
    [3] = "RS_ALU1",
    [4] = "RS_ALU2",
    [5] = "RS_ALU3",
    [6] = "RS_VPU0",
    [7] = "RS_VPU1",
    [8] = "LB",
    [9] = "LFB",
    [10] = "SB",
    [11] = "PRF_INT",
    [12] = "PRF_FLOAT",
  },
  ["SB size"] = 64,
  ["PRF_INT size"] = 192,
  ["FP DIV/SQRT unit native width"] = 32,
  ["LB size"] = 72,
  ["bytes fetched per cycle"] = 32,
  ["FP load latency"] = 7,
  ["nb execution ports"] = 14,
  ["vector-unaligned optimal pattern"] = "1x256",
}
