_cqa_uarch_const = {
  ["ports"] = {
    ["FP ADD"] = {
      [1] = 1,
    },
    ["load"] = {
      [1] = 2,
      [2] = 3,
    },
    ["store address"] = {
      [1] = 2,
      [2] = 3,
      [3] = 7,
    },
    ["misc"] = {
      [1] = 0,
      [2] = 1,
      [3] = 5,
      [4] = 6,
    },
    ["store data"] = {
      [1] = 4,
    },
    ["DIV/SQRT"] = {
      [1] = 0,
    },
    ["FP MUL"] = {
      [1] = 0,
      [2] = 1,
    },
  },
  ["vector-unaligned optimal pattern"] = "1x256",
  ["unlamination threshold"] = 4,
  ["LFB size"] = 10,
  ["Max Loop Buffer bytes"] = 512,
  ["nb FP MUL units"] = 2,
  ["LM size"] = 32,
  ["ROB size"] = 192,
  ["INT vector size in bytes"] = 32,
  ["vector size in bytes"] = 32,
  ["RS size"] = 51,
  ["store unit native width"] = 32,
  ["UQ throughput"] = 4,
  ["PRF size"] = 177,
  ["PRF_INT size"] = 144,
  ["UFS resources"] = {
    [1] = "ROB",
    [2] = "RS",
    [3] = "LB",
    [4] = "LM",
    [5] = "LFB",
    [6] = "SB",
    [7] = "PRF_INT",
    [8] = "PRF_FLOAT",
    [9] = "PRF",
  },
  ["NOP 0f 1f decode"] = "fast",
  ["store latency"] = 3,
  ["load latency"] = 4,
  ["FP load latency"] = 6,
  ["uop cache capacity"] = 1000,
  ["predicted taken branch ports"] = {
    [1] = 6,
  },
  ["PRF_FLOAT size"] = 138,
  ["Max Loop Buffer uops"] = 56,
  ["FP DIV/SQRT unit native width"] = 16,
  ["LB size"] = 72,
  ["IQ throughput"] = 4,
  ["SB size"] = 42,
  ["predec insns per cycle"] = 6,
  ["nb complex decoders"] = 1,
  ["load unit native width"] = 32,
  ["bytes fetched per cycle"] = 16,
  ["retire throughput"] = 4,
  ["nb execution ports"] = 8,
  ["nb simple decoders"] = 3,
}
